add_subdirectory(crypto)
add_subdirectory(primitives)
add_subdirectory(consensus)
add_subdirectory(genesis)
add_subdirectory(chain)
add_subdirectory(explorer)
add_subdirectory(storage)
add_subdirectory(net)
add_subdirectory(wallet)
add_subdirectory(node)
add_subdirectory(rpc)
add_subdirectory(daemon)
add_subdirectory(cli)
